### ISSUE TITLE
The `use-latest-versions.yml` ops file doesn't work because there are no latest releases

### ISSUE THREAD

**Issue by bloeys** [bosh-elastic-stack/elastic-stack-bosh-deployment#11]
Hello, thanks a lot for this repo, its extremely helpful!

One small note is that the latest versions ops files breaks deployment because the releases don't exist. It produces a url like this:  https://github.com/bosh-elastic-stack/elasticsearch-boshrelease/releases/download/latest/elasticsearch-boshrelease-latest.tgz

Which gives a 404.

**Comment by making** [comment]
That ops-file doesn't use `url` for the releases.
What command are you running?

**Comment by bloeys** [comment]
The exact same settings in "TLS / HTTPS / Basic Authentication" section, but I added the latest versions ops file. However on doing that I get a BOSH release not found error.

It deployed fine after removing it.
