### ISSUE TITLE
can i use this repo for deploying ELK on cloudfoundry with BOSH?

### ISSUE THREAD

**Issue by ghost** [bosh-elastic-stack/elastic-stack-bosh-deployment#3]

**Comment by making** [comment]
No, this repo deploys ELK on **BOSH** .

**Comment by ghost** [comment]
yes , I mean I have cloud foundry setup with BOSH2 and i need to do a fresh ELK deployment

**Comment by making** [comment]
If you mean deploying ELK beside your CF (not on your CF), yes you can use this repo.

**Comment by ghost** [comment]
But I want to know why is this repo using old versions of E , L , K and curator.
And I want to use ELk bosh2 bosh release for fetching logs from cloud foundry. Is that possible?

**Comment by making** [comment]
That depends on bosh-releases you use.
You can specify each version in `version.yml`.

Check release pages 
* https://github.com/bosh-elastic-stack/elasticsearch-boshrelease/releases
* https://github.com/bosh-elastic-stack/logstash-boshrelease/releases
* https://github.com/bosh-elastic-stack/kibana-boshrelease/releases

I don't think this rep is using old ELK.

**Comment by making** [comment]
> And I want to use ELk bosh2 bosh release for fetching logs from cloud foundry. Is that possible?

You can use Logstash as a Syslog server using tcp input plugin that receives logs from [firehose-to-syslog](https://github.com/cloudfoundry-community/firehose-to-syslog).

**Comment by ghost** [comment]
actually i  have an existing deployment on bosh1 bosh and now I new to migrate the deployment to bosh2 bosh . In that deployment I am using just these three releases ...
logsearch
logsearch-for-cloudfoundry
cron
and the deployment is a single VM deployment i:e E , L and K in single VM.

**Comment by making** [comment]
I don't get what you mean.

This is not a repo for logsearch.
It's a completely different project.
